name: Build Game

on: push

jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          key: cache_windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
      - name: Install / Update Libraries
        run: |
          haxe -cp build -D analyzer-optimize --run Setup -no-vscheck
      - name: Build Game
        run: |
          haxelib run lime build windows -v -release
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (Windows)
          path: export/release/windows/bin
      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          key: cache_windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          key: cache_linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
      - name: Install LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
      - name: Install / Update Libraries
        run: |
          haxe -cp build -D analyzer-optimize --run Setup
      - name: Build Game
        run: |
          haxelib run lime build linux -v -release
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (Linux)
          path: export/release/linux/bin
      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          key: cache_linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
  build_mac:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          key: cache_mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
      - name: Install / Update Libraries
        run: |
          haxe -cp build -D analyzer-optimize --run Setup
      - name: Build Game
        run: |
          arch -x86_64 haxelib run lime build mac -v -release
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (macOS)
          path: export/release/macos/bin
      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          key: cache_mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
  build_html5:
    name: HTML5 (Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          key: cache_html5
          path: |
            .haxelib/
            export/release/html5/haxe/
            export/release/html5/obj/
      - name: Install / Update Libraries
        run: |
          haxe -cp build -D analyzer-optimize --run Setup
      - name: Build Game
        run: |
          haxelib run lime build html5 -v -release
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (HTML5)
          path: export/release/html5/bin
      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          key: cache_html5
          path: |
            .haxelib/
            export/release/html5/haxe/
            export/release/html5/obj/
  build_hl:
    name: HashLink
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          key: cache_hl
          path: |
            .haxelib/
            export/release/hl/haxe/
            export/release/hl/obj/
      - name: Install / Update Libraries
        run: |
          haxe -cp build -D analyzer-optimize --run Setup
      - name: Install HashLink
        run: |
          haxelib git hashlink https://github.com/HaxeFoundation/hashlink master
          haxelib run lime setup hashlink
      - name: Build Game
        run: |
          haxelib run lime build hl -v -release
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: VS IMPOSTOR Pixel (HashLink)
          path: export/release/hl/bin
      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          key: cache_hl
          path: |
            .haxelib/
            export/release/hl/haxe/
            export/release/hl/obj/
